[project]
name = "misfit-core"
version = "0.1.0"
description = "A tool for create food for test'"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.13"
dependencies = [
    "pytest==8.3.5",
]

[tool.hatch.build.targets.wheel]
package=["src/"]
